= WildFly BOMs

The WildFly BOMs project provides Maven BOM files, which includes dependency management compatible with (same version) WildFly. These files manage the version of the dependencies you may need to build, test or debug your project, ensuring you always get a compatible stack.

The following BOMs are available:

* EJB Client (Maven coordinates "org.wildfly:wildfly-ejb-client-bom", built by /clients/ejb-client/pom.xml)
* EJB Legacy Client (Maven coordinates "org.wildfly:wildfly-ejb-client-legacy-bom", built by /clients/ejb-legacy-client/pom.xml)
* JAXWS Client (Maven coordinates "org.wildfly:wildfly-jaxws-client-bom", built by /clients/jaxws-client/pom.xml)
* JMS Client (Maven coordinates "org.wildfly:wildfly-jms-client-bom", built by /clients/jms-client/pom.xml)
* Jakarta EE 8 (Maven coordinates "org.wildfly.bom:wildfly-jakartaee8", built by /jakartaee8/pom.xml)
* Jakarta EE 8 with Tools (Maven coordinates "org.wildfly.bom:wildfly-jakartaee8-with-tools", built by /jakartaee8/jakartaee8-with-tools/pom.xml)
* MicroProfile (Maven coordinates "org.wildfly.bom:wildfly-microprofile", built by /microprofile/pom.xml)

== Usage

To use a BOM, import into your dependency management. For example, if you want "Jakarta EE 8 with Tools" artifacts, use:

[source, xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.wildfly.bom</groupId>
            <artifactId>wildfly-jakartaee8-with-tools</artifactId>
            <scope>import</scope>
            <type>pom</type>
            <version>${wildfly.version}</version>
        </dependency>
    </dependencies>
</dependencyManagement> 
----
