/*
 * Copyright The WildFly Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package org.jboss.as.test.txbridge.fromjta.service;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import org.jboss.logging.Logger;

import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 */
@WebServiceClient(name = "FirstServiceATService", targetNamespace = "http://www.jboss.com/jbossas/test/txbridge/fromjta/first")
public class FirstServiceATService extends Service {
    private static final Logger log = Logger.getLogger(FirstServiceATService.class.getName());

    private static final URL FIRSTSERVICEATSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = FirstServiceATService.class.getResource(".");
            url = new URL(baseUrl, "FirstServiceAT.wsdl");
        } catch (MalformedURLException e) {
            log.warn("Failed to create URL for the wsdl Location: 'FirstServiceAT.wsdl', retrying as a local file", e);
        }
        FIRSTSERVICEATSERVICE_WSDL_LOCATION = url;
    }

    public FirstServiceATService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirstServiceATService() {
        super(FIRSTSERVICEATSERVICE_WSDL_LOCATION,
            new QName("http://www.jboss.com/jbossas/test/txbridge/fromjta/First", "FirstServiceATService"));
    }

    @WebEndpoint(name = "FirstServiceAT")
    public FirstServiceAT getFirstServiceAT() {
        return super.getPort(
            new QName("http://www.jboss.com/jbossas/test/txbridge/fromjta/First", "FirstServiceAT"),
            FirstServiceAT.class);
    }

    /**
     * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.
     *   Supported features not in the <code>features</code> parameter will have their default values.
     */
    @WebEndpoint(name = "FirstServiceAT")
    public FirstServiceAT getFirstServiceAT(WebServiceFeature... features) {
        return super.getPort(
            new QName("http://www.jboss.com/jbossas/test/txbridge/fromjta/First", "FirstServiceAT"),
            FirstServiceAT.class, features);
    }

}
