[[How_to_Add_a_Test_Case]]
= How to Add a Test Case

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Thank you for finding time to contribute to WildFly quality.
Covering corner cases found by community users with tests is very important to increase stability.
If you're providing a test case to support your bug report,
it's very likely that your bug will be fixed much sooner.

[[create-a-test-case.]]
== Create a test case

Don't be discouraged, it's quite easy - a simple use case may even consist of a single short `.java` file.

Check WildFly https://github.com/wildfly/wildfly/tree/main/testsuite/integration/basic/src/test/java/org/jboss/as/test/integration[test suite test cases] for examples.

For more information, see <<WildFly_Testsuite_Test_Developer_Guide,WildFly Testsuite Test Developer Guide>>.
Check the requirements for a test to be included in the testsuite.

Ask for help at WildFly Google user group or Zulip chat.

[[push-your-test-case-to-github-and-create-a-pull-request.]]
== Push your test case to GitHub and create a pull request.

For information on how to create a GitHub account and push your code therein,
see link:Hacking_On_WildFly{outfilesuffix}[Hacking on WildFly].
