[[WildFly_Integration_Testsuite_User_Guide]]
= WildFly Integration Testsuite User Guide

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

*See also:* <<WildFly_Testsuite_Test_Developer_Guide,WildFly Testsuite Test Developer Guide>>

*Target Audience:* Those interested in running the testsuite or a subset
thereof, with various configuration options.

[[running-the-testsuite]]
== Running the testsuite

The WildFly source code includes scripts to assist with building WildFly and running the testsuite. *Using these scripts is not required.* The scripts simply provide some convenience wrappers around directly calling `mvn`.
Directly using `mvn` is fine and is commonly done.

Tests are run either when running the `build.sh` and `build.bat` shell scripts, or by using `integration-tests.sh` or `integration-tests.bat`. All of these scripts are found in the root directory of the source tree.

* `build.sh` or `build.bat`, as a part of the WildFly build.
** By default, only smoke tests are run. To run all tests, use `./build.sh install -DallTests`.
* `integration-tests.sh` or `integration-tests.bat`, a convenience script which runs all parent testsuite modules (which configure the server).
* Direct Maven invocation, using `mvn install`.

The scripts are wrappers around the Maven-based build. Their arguments are
passed to Maven (with few exceptions described below). This means you
can use:

* `./build.sh` (defaults to install)
* `./build.sh install`
* `./build.sh clean install`
* `./integration-tests.sh install`
* ...etc.

[[supported-maven-phases]]
=== Supported Maven phases

Testsuite actions are bounds to various Maven phases up to `verify`.
Running the build with earlier phases may fail in the submodules due to
missed configuration steps. Therefore, the only Maven phases you may
safely run, are:

* clean
* install
* site

The `test` phase is not recommended to be used for scripted jobs as we
are planning to switch to the `failsafe` plugin bound to the
`integration-test` and `verify` phases. See
https://redhat.atlassian.net/browse/WFLY-625[WFLY-625] and
https://redhat.atlassian.net/browse/WFLY-228[WFLY-228].

[[testsuite-structure]]
=== Testsuite structure

....
testsuite/
  domain/
  galleon/
  integration/
    smoke/
    basic/
    clustering/
    iiop/
    multinode/
    xts/
    manualmode/
    web/
    ws/
  layers/
  layers-expansion/
  mixed-domain/
  preview/
  scripts/
....

[[test-groups]]
=== Test groups

To define groups of tests to be run, these properties are available:

* `-DallTests` - Runs all subgroups.
* `-DallInteg` - Runs all integration tests. Same as
`cd testsuite/integration; mvn clean install -DallTests`
* `-Dts.integ` - Basic integration + clustering tests.
* `-Dts.clustering` - Clustering tests.
* `-Dts.iiop` - IIOP tests.
* `-Dts.multinode` - Tests with many nodes.
* `-Dts.manualmode` - Tests with manual mode Arquillian containers.
* `-Dts.domain` - Domain mode tests.
* `-Dts.bootable` - Bootable jar tests.
* `-Dts.layers` - Slimmed server / galleon layers tests.
* `-Dts.microprofile` - MicroProfile tests.
* `-Dts.standalone.microprofile` - Standalone MicroProfile tests.
* `-Dts.preview` - Preview server tests.
* `-Dts.bootable.preview` - Preview bootable jar tests.

[[examples]]
== Examples

* `./integration-tests.sh install` -- Runs smoke tests.
* `./integration-tests.sh clean install` -- Cleans the target directory, then runs smoke tests.
* `./integration-tests.sh install -Dts.smoke` -- Same as above.
* `./integration-tests.sh install -DallTests` -- Runs all testsuite tests.
* `./build.sh clean test` -- Run the default module and its tests.
* `./build.sh clean test -Ddomain-tests -Dintegration.module -Dbasic.integration.tests` -- Run a selected set of modules and tests.

*Pure maven* - if you prefer not to use scripts, you may achieve the
same result with:

* `mvn ... -rf testsuite`

The `-rf ...` parameter stands for "resume from" and causes Maven to run
the specified module _and all successive_.

It's possible to run only a single module (provided the ancestor modules were already run to create the AS copies):

* `mvn ... -pl testsuite/integration/clustering`

The `-pl ...` parameter stands for "project list" and causes Maven to
run the specified module _only_.

[[output-to-console]]
=== Output to console

[source,java,options="nowrap"]
----
-DtestLogToFile
----

[[other-options]]
=== Other options

`-DnoWebProfile` - Run all tests with the _full_ profile (
`standalone-full.xml`). By default, most tests are run under _web_
profile ( `standalone.xml`).

`-Dts.skipTests` - Skip testsuite's tests. Defaults to the value of
`-DskipTests`, which defaults to `false`. To build AS, skip unit tests
and run testsuite, use `-DskipTests -Dts.skipTests=false`.

[[timeouts]]
=== Timeouts

[[surefire-execution-timeout]]
==== Surefire execution timeout

Unfortunatelly, no math can be done in Maven, so instead of applying a
timeout ratio, you need to specify timeout manually for Surefire.

[source,java,options="nowrap"]
----
-Dsurefire.forked.process.timeout=900
----

[[in-test-timeout-ratios]]
==== In-test timeout ratios

Ratio in prercent - 100 = default, 200 = two times longer timeouts for
given category.

Currently we have five different ratios. Later, it could be replaced
with just one generic, one for database and one for deployment
operations.

[source,java,options="nowrap"]
----
-Dtimeout.ratio.fsio=100
-Dtimeout.ratio.netio=100
-Dtimeout.ratio.memio=100
-Dtimeout.ratio.proc=100
-Dtimeout.ratio.db=100
----

[[running-a-single-test-or-specified-tests]]
=== Running a single test (or specified tests)

Single test is run using *-Dtest=...* . Examples:

* `./integration-tests.sh install` `+-Dtest='*Clustered*'+` `-Dintegration.module` `-Dts.clustering`
* `./integration-tests.sh clean install -Dtest=org` `/` `jboss` `/` `as`
`/` `test` `/` `integration` `/` `ejb/async/*TestCase.java`
`-Dintegration.module` `-Dts.basic`
* `cd testsuite; mvn install` `+-Dtest='*Clustered*'+`
`-Dts.basic`
`# No need for -Dintegration.module - integration module is active by default.`

The same shortcuts listed in "Test groups" may be used to activate the
module and group profile.

Note that `-Dtest=` overrides `<includes>` and `<exludes>` defined in
pom.xml, so do not rely on them when using wildcards - all compiled test
classes matching the wildcard will be run.

*Which Surefire execution is used?*

Due to Surefire's design flaw, tests run multiple times if there are
multiple surefire executions. +
To prevent this, if `-Dtest=`... is specified, non-default executions
are disabled, and standalone-full is used for all tests. +
If you need it other way, you can overcome that need:

* `basic-integration-web.surefire with standalone.xml - Configure standalone.xml to be used as server config.`
* `basic-integration-non-web.surefire - For tests included here, technically nothing changes.`
* `basic-integration-2nd.surefire - Simply run the second test in another invocation of Maven.`

[[running-against-existing-as-copy-not-the-one-from-buildtargetjboss-as-]]
=== Running against existing AS copy (not the one from
build/target/jboss-as-*)

*-Djboss.dist=<path/to/jboss-as>* will tell the testsuite to copy that
AS into submodules to run the tests against.

For example, you might want to run the testsuite against AS located in
`/opt/wildfly-8` :

[source,java,options="nowrap"]
----
./integration-tests.sh -DallTests -Djboss.dist=/opt/wildfly-8
----

The difference between jboss.dist and jboss.home:

jboss.dist is the location of the tested binaries. It gets copied to
testsuite submodules.

jboss.home is internally used and points to those copied AS instances
(for multinode tests, may be even different for each AS started by
Arquillian).

[[running-against-a-running-jboss-as-instance]]
==== Running against a running JBoss AS instance

Arquillian's WildFly container adapter allows specifying
`allowConnectingToRunningServer` in `arquillian.xml`, which makes it
check whether AS is listening at `managementAddress:managementPort`, and
if so, it uses that server instead of launching a new one, and doesn't
shut it down at the end.

All arquillian.xml's in the testsuite specify this parameter. Thus, if
you have a server already running, it will be re-used.

[[running-with-a-debugger]]
=== Running with a debugger

[cols=",,,",options="header"]
|=======================================================================
|Argument |What will start with debugger |Default port |Port change arg.

|-Ddebug |AS instances run by Arquillian |8787 |-Das.debug.port=...

|-Djpda |alias for -Ddebug |  |

|-DdebugClient |Test JVMs (currently Surefire) |5050
|-Ddebug.port.surefire=...

|-DdebugCLI |AS CLI |5051 |-Ddebug.port.cli=...
|=======================================================================

[[examples-1]]
==== Examples

[source,shell,options="nowrap"]
----
./integration-tests.sh install -DdebugClient -Ddebug.port.surefire=4040

...

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Listening for transport dt_socket at address: 4040
----

[source,options="nowrap"]
----
./integration-tests.sh install -DdebugClient -Ddebug.port.surefire

...

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Listening for transport dt_socket at address: 5050
----

[source,shell,options="nowrap"]
----
./integration-tests.sh install -Ddebug
----

[source,shell,options="nowrap"]
----
./integration-tests.sh install -Ddebug -Das.debug.port=5005
----

[IMPORTANT]

JBoss AS is started by Arquillian, when the first test which requires
given instance is run. Unless you pass *-DtestLogToFile=false,* *there's
(currently) no challenge text in the console*; it will look like the
first test is stuck. This is being solved in
http://jira.codehaus.org/browse/SUREFIRE-781.

[IMPORTANT]

Depending on which test group(s) you run, multiple AS instances may be
started. In that case, you need to attach the debugger multiple times.

==== Debugging clustering tests

With the implementation of https://redhat.atlassian.net/browse/WFLY-276[WFLY-276] for the clustering test suite module,
these tests can be run with the debugger as well.
Here are some tips on how to effectively debug:

1. Prepare your IDE with 4 remote debugger sessions templates: `node1` with port 8787, `node2` with port 8788, `node3` with port 8789, and `node4` with port 8790.
2. Using `mvn`, run a single test (`-Dtest=..`) in the debug mode (`-Ddebug` / `-Djpda`)
3. Connect the debugger to each node as they are starting since the JVM is configured to wait for the debugger connection to proceed.
4. Keep connecting to starting nodes as some tests change the topology during the test.

NOTE: Container start timeout in Arquillian is currently set to 60 seconds,
you may need to increase the timeout depending on your swiftness with connecting the remote debugger.


[[running-tests-with-ipv6]]
=== Running tests with IPv6

`-Dipv6` - Runs AS with
`-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true`

and the following defaults, overridable by respective parameter:

[cols=",,,",options="header"]
|=======================================================================
|Parameter |IPv4 default |IPv6 default |

|-Dnode0 |127.0.0.1 |::1 |Single-node tests.

|-Dnode1 |127.0.0.1 |::1 |Two-node tests (e.g. cluster) use this for the
2nd node.

|-Dmcast |230.0.0.4 |ff01::1 |ff01::1 is IPv6 Node-Local scope mcast
addr.

|-Dmcast.jgroupsDiag |224.0.75.75 |ff01::2 |JGroups diagnostics
multicast address.

|-Dmcast.modcluster |224.0.1.105 |ff01::3 |mod_cluster multicast
address.
|=======================================================================

Values are set in AS configuration XML, replaced in resources (like
ejb-jar.xml) and used in tests.

[[running-tests-with-security-manager-custom-security-policy]]
=== Running tests with security manager / custom security policy

`-Dsecurity.manager` - Run with default policy.

`-Dsecurity.policy=<path>` - Run with the given policy.

`-Dsecurity.manager.other=<set of Java properties>` - Run with the given
properties. Whole set is included in all server startup parameters.

Example:

[source,options="nowrap"]
----
./integration-tests.sh clean install -Dintegration.module -DallTests \
\"-Dsecurity.manager.other=-Djava.security.manager \
-Djava.security.policy==$(pwd)/testsuite/shared/src/main/resources/secman/permitt_all.policy \
-Djava.security.debug=access:failure \"
----

Notice the \" quotes delimiting the whole `-Dsecurity.manager.other`
property.

[[creating-test-reports]]
=== Creating test reports

Test reports are created in the form known from EAP 5. To create them,
simply run the testsuite, which will create Surefire XML files.

Creation of the reports is bound to the `site` Maven phase, so it must
be run separately afterward. Use one of these:

[source,options="nowrap"]
----
./integration-tests.sh site
cd testsuite; mvn site
mvn -pl testsuite site
----

Note that it will take all test results under `testsuite/integration/` -
the pattern is `**/*TestCase.xml`, without need to specify `-DallTests`.

[[creating-coverage-reports]]
=== Creating coverage reports

*Jira:* https://redhat.atlassian.net/browse/WFLY-585

Coverage reports are created by
http://www.eclemma.org/jacoco/trunk/index.html[JaCoCo].

During the integration tests, Arquillian is passed a JVM argument which
makes it run with JaCoCo agent, which records the executions into
`${basedir}/target/jacoco` .

In the `site` phase, a HTML, XML and CSV reports are generated. That is
done using `jacoco:report` Ant task in `maven-ant-plugin` since JaCoCo's
maven report goal doesn't support getting classes outside
target/classes.

[[usage-integration-testsuite]]
==== Usage

[source,options="nowrap"]
----
./build.sh clean install -DskipTests
./integration-tests.sh clean install -DallTests -Dcoverage
./integration-tests.sh site -DallTests -Dcoverage ## Must run in separatedly.
----

Alternative:

[source,options="nowrap"]
----
mvn clean install -DskipTests
mvn -rf testsuite clean install -DallTests -Dcoverage
mvn -rf testsuite site -DallTests -Dcoverage
----

[[cleaning-the-project]]
=== Cleaning the project

To have most stable build process, it should start with:

* clean target directories
* only central Maven repo configured
* clean local repository or at least:
** free of artefacts to be built
** free of dependencies to be used (especially snapshots)

To use , you may use these commands:

[source,options="nowrap"]
----
mvn clean install -DskipTests -DallTests  ## ...to clean all testsuite modules.
mvn dependency:purge-local-repository build-helper:remove-project-artifact -Dbuildhelper.removeAll
----

In case the build happens in a shared environment (e.g. network disk),
it's recommended to use local repository:

[source,shell,options="nowrap"]
----
cp /home/jenkins/.m2/settings.xml .
sed "s|<settings>|<settings><localRepository>/home/jenkins/jenkins-repos/$JOBNAME</localRepository>|" -i settings.xml
----

Or:

[source,shell,options="nowrap"]
----
mvn clean install ... -Dmaven.repo.local=localrepo
----

See also https://redhat.atlassian.net/browse/WFLY-628.

[[building-server-configurations]]
== Building server configurations

Whenever we fire a surefire execution, this causes Arquillian to start a server(s), execute tests and then shutdown
the server(s). Starting a server in multiple executions kills the test logs of previous executions, and so it's recommended
to create a new named server configuration for each surefire execution.

When we build a server configuration, we need to carry out several steps:

* Provision the server installation to be tested
* Perhaps edit some configuration files (e.g. parametrizing the test cases for IP addresses, default databases and the like)
* Perhaps copy in some modules

Provisioning server installations is achieved in two different ways, depending on requirements:

=== maven-resources-plugin based provisioning

In the root `testsuite/pom.xml` file there is a maven-resources-plugin execution `ts.copy-wildfly` that in the `process-test-resources` phase copies most of the content of a WildFly build to the current project's
`testsuite/wildfly` directory. The `modules` directory content is not copied, so, when using such an installation, the server's `module.path` must be configured to include the `modules` dir of the original WildFly build.

The original WildFly build is found in either the `build`, `ee-build`, `legacy/ee-feature-pack/build`, `legacy/ee-feature-pack/ee-build` or `preview/build` module, or in an externally provided location, depending on the
configuration of the maven build.

A module or profile that does not want a server installation to be provisioned this way can disable this provisioning by setting the `phase` of the `ts.copy-wildfly` execution to `none`.

=== Galleon based provisioning with the wildfly-maven-plugin

Here the wildfly-maven-plugin `provision` goal is used to provision a server using Galleon. The feature-packs and layers to use are controlled by the configuration of each plugin execution.

=== Customizing the management configuration of a provisioned server

The general recommendation for customizing the management configuration of a provisioned server is to implement a `ServerSetupTask` and configure the relevant test classes to use it via the `ServerSetup` annotation.

If using `ServerSetupTask` isn't suitable (e.g. if the configuration settings need to be present for all tests against the installation), then JBoss CLI `.cli` scripts can be added to the test module's source and executed before
the test phase begins using the wildfly-maven-plugin's `execute` goal.

There is some legacy code that does configuration modification via ant and xslt. This is being replaced and no new uses of this technique should be added.

=== Adding JBoss Modules modules to the provisioned server

The general recommendation for adding JBoss Modules modules that a test needs is to use the
`TestModule` utility class from within the relevant test class.

If this approach isn't suitable, the maven-resources-plugin can be used.

=== Other server installation customization

Addition of other content to the server installation can be done using the `maven-resources-plugin`. The `testsuite/integration/pom.xml` includes an execution that adds properties files to the `standalone/configuration` dir that
provide users, credentials and groups that integration tests often expect.

[[parameterization-of-testsuite-runs]]
== Parameterization of testsuite runs

The `testsuite/pom.xml` contains a properties section which should hold all globally defined properties required to run
the testsuite and their defaults (e.g. IP addresses, IP stack configs, database configs, etc).
These properties will then be inherited by all of the testsuite modules.

This allows substitution of properties specified on the command line, such as:

[source,shell]
----
mvn clean test -Dintegration.module -Dclustering.integration.tests -Dnode0=192.168.0.1 -Dnode1=192.168.0.2
----

[[Changing_the_container_images_used_in_integration_tests]]
== Changing the container images used in integration tests

In integration tests, we use the following images:

* `otel/opentelemetry-collector`
* `docker.elastic.co/elasticsearch/elasticsearch`
* `apache/james`
* `apache/kafka-native`
* `quay.io/arkmq-org/activemq-artemis-broker`
* `quay.io/keycloak/keycloak`

It is possible to override the default images and versions by using:

* System properties, e.g. `-Dtestsuite.kafka-native.image=apache/kafka-native:3.9.0`
* Environment variables, e.g. `AS_TS_KAFKA_NATIVE_IMAGE=apache/kafka-native:3.9.0`
* Properties file specified via `testsuite.config.properties` system property or `TESTSUITE_CONFIG_PROPERTIES` environment variable, e.g. `-Dtestsuite.config.properties=/path/to/testsuite-config.properties` or
`TESTSUITE_CONFIG_PROPERTIES=/path/to/testsuite-config.properties`; the properties file format has to be the same as for system properties, e.g.:

[source,properties]
----
testsuite.opentelemetry-collector.image=otel/opentelemetry-collector:0.115.1
testsuite.elasticsearch.image=docker.elastic.co/elasticsearch/elasticsearch:8.15.4
testsuite.mailserver.image=apache/james:demo-3.8.2
testsuite.kafka-native.image=apache/kafka-native:3.8.0
testsuite.activemq-artemis-broker.image=quay.io/arkmq-org/activemq-artemis-broker:artemis.2.42.0
testsuite.keycloak.image=quay.io/keycloak/keycloak:24.0.2
----
