[[WildFly_Testsuite_Harness_Developer_Guide]]
= WildFly Testsuite Harness Developer Guide

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

The testsuite implementation was tracked by https://issues.redhat.com/browse/WFLY-576[WFLY-576],
which still contains a lot of useful information.

[[adding-a-new-maven-plugin]]
== Adding a new maven plugin

The plugin version needs to be specified in jboss-parent at the `<properties>` section of the jboss-parent https://github.com/jboss/jboss-parent-pom/blob/main/pom.xml[pom.xml] file.

[[how-the-as-instance-is-built]]
== How the AS instance is built

See <<How_the_server_is_built_and_configured_for_testsuite_modules,How the JBoss AS instance is built and configured
for testsuite modules.>>

[[properties-and-their-propagation]]
== Properties and their propagation

Propagated to tests through arquillian.xml: +
`<property name="javaVmArguments">${server.jvm.args}</property>` +
TBD: https://issues.redhat.com/browse/ARQ-647

[[jboss-as-instance-dir]]
=== JBoss AS instance dir

*integration/pom.xml*

(currently nothing)

**-arquillian.xml*

[source,xml,options="nowrap"]
----
<container qualifier="jboss" default="true">
    <configuration>
        <property name="jbossHome">${basedir}/target/jbossas</property>
----

[[server-jvm-arguments]]
=== Server JVM arguments

[source,xml,options="nowrap"]
----
<surefire.memory.args>-Xmx512m -XX:MaxPermSize=256m</surefire.memory.args>
<surefire.jpda.args></surefire.jpda.args>
<surefire.system.args>${surefire.memory.args} ${surefire.jpda.args}</surefire.system.args>
----

[[ip-settings]]
=== IP settings

* `${ip.server.stack}` used in `<systemPropertyVariables>/<server.jvm.args>` which is used in `*-arquillian.xml`.

[[testsuite-directories]]
=== Testsuite directories

* `${jbossas.ts.integ.dir`}
* `${jbossas.ts.dir`}
* `${jbossas.project.dir`}

[[clustering-properties]]
=== Clustering properties

* node0
* node1

== Debug parameters propagation

[source,xml,options="nowrap"]
----
<surefire.jpda.args></surefire.jpda.args>       - default

<surefire.jpda.args>-Xrunjdwp:transport=dt_socket,address=${as.debug.port},server=y,suspend=y</surefire.jpda.args> - activated by -Ddebug or -Djpda


testsuite/pom.xml:        <surefire.system.args>... ${surefire.jpda.args} ...</surefire.system.args>
testsuite/pom.xml:                        <jboss.options>${surefire.system.args}</jboss.options>

testsuite/integration/pom.xml:     <server.jvm.args>${surefire.system.args} ${jvm.args.ip.server} ${jvm.args.security} ${jvm.args.timeouts} -Dnode0=${node0} -Dnode1=


integration/pom.xml:
<server.jvm.args>${surefire.system.args} ${jvm.args.ip.server} ${jvm.args.security} ${jvm.args.timeouts} -Dnode0=${node0} -Dnode1=${node1} -DudpGroup=${udpGroup} ${jvm.args.dirs}</server.jvm.args>

arquillian.xml:
<property name="javaVmArguments">${server.jvm.args} -Djboss.inst=${basedir}/target/jbossas</property>
----

[[How_the_server_is_built_and_configured_for_testsuite_modules]]
== How the WildFly is built and configured for testsuite modules

WildFly instance is copied from `${jboss.dist}` to `testsuite/target/jbossas`.
This defaults to WildFly which is built by the project (`build/target/wildfly-*`).

*testsuite/pom.xml*

From `${jboss.home}` to `${basedir}/target/jbossas` phase `generate-test-resources`, goal `resource-plugin:copy-resources`

*testsuite/integration/pom.xml*

phase process-test-resources: antrun-plugin:

[source,xml,options="nowrap"]
----
<ant antfile="${basedir}/src/test/scripts/basic-integration-build.xml">
    <target name="build-basic-integration"/>
    <target name="build-basic-integration-jts"/>
</ant>
----

Which invokes:

[source,xml,options="nowrap"]
----
<target name="build-basic-integration" description="Builds server configuration for basic-integration tests">
    <build-server-config name="jbossas"/>
    <!-- .. -->
</target>
----

Which invokes:

[source,xml,options="nowrap"]
----
<!-- Copy the base distribution. -->
<!-- We exclude modules and bundles as they are read-only and we locate the via sys props. -->
<copy todir="@{output.dir}/@{name}">
    <fileset dir="@{jboss.dist}">
        <exclude name="**/modules/**"/>
        <exclude name="**/bundles/**"/>
    </fileset>
</copy>

<!-- overwrite with configs from test-configs and apply property filtering -->
<copy todir="@{output.dir}/@{name}" overwrite="true" failonerror="false">
    <fileset dir="@{test.configs.dir}/@{name}"/>
    <filterset begintoken="${" endtoken="}">
        <filter token="node0" value="${node0}"/>
        <filter token="node1" value="${node1}"/>
        <filter token="udpGroup" value="${udpGroup}"/>
        <filter-elements/>
    </filterset>
</copy>
----

[[arquillian-config-file-location]]
=== Arquillian config file location

[source,options="nowrap"]
----
-Darquillian.xml=some-file-or-classpath-resource.xml
----
