/*
 * Generated by XDoclet - Do not edit!
 */
package org.jboss.as.test.integration.ejb.entity.cmp.relationship.oneToOneBidirectionalWithTableMapping;

/**
 * Local home interface for Child.
 */
public interface ChildLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ChildLocal";
   public static final String JNDI_NAME="java:global/one2one-table-mapping/Child!org.jboss.as.test.integration.ejb.entity.cmp.relationship.oneToOneBidirectionalWithTableMapping.ChildLocalHome";

   public ChildLocal create(ChildPK pk) throws javax.ejb.CreateException;

   public ChildLocal findByPrimaryKey(ChildPK pk) throws javax.ejb.FinderException;

}
