/*
 * Generated by XDoclet - Do not edit!
 */
package org.jboss.as.test.integration.ejb.entity.cmp.relationship.oneToOneBidirectionalWithTableMapping;

/**
 * Local home interface for Parent.
 */
public interface ParentLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ParentLocal";
   public static final String JNDI_NAME="java:global/one2one-table-mapping/Parent!org.jboss.as.test.integration.ejb.entity.cmp.relationship.oneToOneBidirectionalWithTableMapping.ParentLocalHome";

   public ParentLocal create(ParentPK pk) throws javax.ejb.CreateException;

   public ParentLocal findByPrimaryKey(ParentPK pk) throws javax.ejb.FinderException;

}
