/*
 * Generated by XDoclet - Do not edit!
 */
package org.jboss.as.test.integration.ejb.entity.cmp.relationship.oneToOneBidirectionalWithTableMapping;

/**
 * Local interface for Parent.
 */
public interface ParentLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.Integer getId(  ) ;

   public java.lang.String getName(  ) ;

   public void setName( java.lang.String name ) ;

   public org.jboss.as.test.integration.ejb.entity.cmp.relationship.oneToOneBidirectionalWithTableMapping.ChildLocal getChild(  );

   public void setChild( org.jboss.as.test.integration.ejb.entity.cmp.relationship.oneToOneBidirectionalWithTableMapping.ChildLocal c ) ;

}
