package org.jboss.as.ejb3.util;

public enum MdbValidityStatus {

    MDB_CANOT_BE_AN_INTERFACE, MDB_CLASS_CANNOT_BE_PRIVATE_ABSTRACT_OR_FINAL, MDB_ON_MESSAGE_METHOD_CANT_BE_FINAL,
    MDB_MESSAGE_METHOD_CANT_BE_STATIC, MDB_ON_MESSAGE_CANT_BE_PRIVATE, MDB_SHOULD_NOT_HAVE_FINALIZE_METHOD, MDB_IS_VALID;
}
