[[Jakarta_Server_Faces]]
= Jakarta Server Faces Configuration

[abstract]

Jakarta Server Faces configuration is handled by the Jakarta Server Faces subsystem. The Jakarta Server Faces subsystem
allows multiple Jakarta Server Faces implementations to be installed on the same WildFly server. In particular, any
version that implements spec level 4.0 or higher can be installed. For each Jakarta Server Faces
implementation, a new slot needs to be created under `jakarta.faces.impl`, `jakarta.faces.api`, and
`org.jboss.as.jsf-injection`. When the Jakarta Server Faces subsystem starts up, it scans the module path to find all
the Jakarta Server Faces implementations that have been installed. The default Jakarta Server Faces implementation that
WildFly should use is defined by the `default-jsf-impl-slot` subsystem attribute.

[[installing-a-new-jsf-implementation-via-feature-pack]]
== Installing a new Jakarta Server Faces implementation via a feature pack

WildFly supports provisioning a server using the Galleon tool, which allows an administrator to provision a server with
only the desired features, which are delivered as feature packs. For more information, see link:/Galleon_Provisioning{outfilesuffix}[Provisioning WildFly with Galleon].
For an example of such a feature pack, see the https://github.com/wildfly-extras/wildfly-myfaces-feature-pack[WildFly MyFaces Feature Pack]
project in the WildFly Extras GitHub organization.

As a quick start, to provision a server using this feature pack, one might use a commandline like the following:

[source,bash]
-----
$ galleon.sh provision myfaces_server.xml --dir=$SERVER_DIR
-----

.myfaces_server.xml
[source,xml]
-----
<?xml version="1.0" ?>
<installation xmlns="urn:jboss:galleon:provisioning:3.0">
  <feature-pack location="org.wildfly:wildfly-galleon-pack:{wildfly.version}">
    <default-configs inherit="true"/>
    <packages inherit="true"/>
  </feature-pack>
  <feature-pack location="org.wildfly:wildfly-myfaces-feature-pack:{feature-pack.version}">
    <default-configs inherit="true"/>
    <packages inherit="true"/>
  </feature-pack>
  <config model="standalone" name="standalone.xml">
    <layers>
      <!-- Base layer -->
      <include name="management"/>
      <include name="myfaces"/>
    </layers>
  </config>
  <options>
    <option name="optional-packages" value="passive+"/>
    <option name="jboss-fork-embedded" value="true"/>
  </options>
</installation>
-----

[[manually-installing-a-new-jsf-implementation]]
== Manually installing a new Jakarta Server Faces implementation

A new Jakarta Server Faces implementation can be manually installed as follows:

[[add-a-module-slot-for-the-new-jsf-implementation-jar]]
=== Add a module slot for the new Jakarta Server Faces implementation JAR

* Create the following directory structure under the WILDFLY_HOME/modules directory: +
`WILDFLY_HOME/modules/jakarta/faces/impl/<JSF_IMPL_NAME>-<JSF_VERSION>` +
+
For example, for MyFaces 4.0.0, the above path would resolve to: +
`WILDFLY_HOME/modules/jakarta/faces/impl/myfaces-4.0.0`

* Place the Jakarta Server Faces implementation JAR in the <JSF_IMPL_NAME>-<JSF_VERSION> subdirectory. In the same
subdirectory, add a `module.xml` file similar to the link:downloads/mojarra-impl-module.xml[Mojarra] or
link:downloads/myfaces-impl-module.xml[MyFaces] template examples. Change the `resource-root-path` to the name of your
Jakarta Server Faces implementation JAR and fill in appropriate values for ${`jsf-impl-name`} and ${ `jsf-version`}.

[[add-a-module-slot-for-the-new-jsf-api-jar]]
=== Add a module slot for the new Jakarta Server Faces API JAR

* Create the following directory structure under the WILDFLY_HOME/modules directory: +
WILDFLY_HOME/modules/jakarta/faces/api/<JSF_IMPL_NAME>-<JSF_VERSION>

* Place the JSF API JAR in the <JSF_IMPL_NAME>-<JSF_VERSION> subdirectory. In the same subdirectory, add a `module.xml`
file similar to the link:downloads/mojarra-api-module.xml[Mojarra] or link:downloads/myfaces-api-module.xml[MyFaces]
template examples. Change the `resource-root-path` to the name of your Jakarta Server Faces API JAR and fill in appropriate
values for ${ `jsf-impl-name`} and ${ `jsf-version`}.

[[add-a-module-slot-for-the-jsf-injection-jar]]
=== Add a module slot for the Jakarta Server Faces injection JAR

* Create the following directory structure under the WILDFLY_HOME/modules directory: +
`WILDFLY_HOME/modules/org/jboss/as/jsf-injection/<JSF_IMPL_NAME>-<JSF_VERSION>`

* Copy the wildfly-jsf-injection JAR and the weld-core-jsf JAR from `WILDFLY_HOME/modules/system/layers/base/org/jboss/as/jsf-injection/main`
to the <JSF_IMPL_NAME>-<JSF_VERSION> subdirectory.

* In the <JSF_IMPL_NAME>-<JSF_VERSION> subdirectory, add a `module.xml` file similar to the link:downloads/mojarra-injection-module.xml[Mojarra]
or link:downloads/myfaces-injection-module.xml[MyFaces] template examples and fill in appropriate values for ${`jsf-impl-name`},
${ `jsf-version`}, ${ `version.jboss.as`}, and ${`version.weld.core`}. (These last two placeholders depend on the versions
of the wildfly-jsf-injection and weld-core-jsf JARs that were copied over in the previous step.)

////
[[for-myfaces-only---add-a-module-for-the-commons-digester-jar]]
=== For MyFaces only - add a module for the commons-digester JAR

* Create the following directory structure under the WILDFLY_HOME/modules directory: +
WILDFLY_HOME/modules/org/apache/commons/digester/main

* Place the
http://search.maven.org/remotecontent?filepath=commons-digester/commons-digester/1.8/commons-digester-1.8.jar[commons-digester]
JAR in WILDFLY_HOME/modules/org/apache/commons/digester/main. In the
`main` subdirectory, add a `module.xml` file similar to this
https://github.com/wildfly/wildfly/blob/main/jsf/multi-jsf-installer/src/main/resources/myfaces-digester-module.xml[template].
Fill in the appropriate value for $\{ `version.commons-digester`}.
////

[[start-the-server]]
=== Start the server

After starting the server, the following CLI command can be used to verify that your new Jakarta Server Faces
implementation has been installed successfully. The new Jakarta Server Faces implementation should appear in the output
of this command.

[source,options="nowrap"]
----
[standalone@localhost:9990 /] /subsystem=jsf:list-active-jsf-impls()
----

[[changing-the-default-jsf-implementation]]
== Changing the default Jakarta Server Faces implementation

The following CLI command can be used to make a newly installed Jakarta Server Faces implementation the default Jakarta
Server Faces implementation used by WildFly:

[source,options="nowrap"]
----
/subsystem=jsf/:write-attribute(name=default-jsf-impl-slot,value=<JSF_IMPL_NAME>-<JSF_VERSION>)
----

A server restart will be required for this change to take effect.

[[configuring-a-jsf-app-to-use-a-non-default-jsf-implementation]]
== Configuring a Jakarta Server Faces app to use a non-default Jakarta Server Faces implementation

A Jakarta Server Faces app can be configured to use an installed Jakarta Server Faces implementation that's not the
default implementation by adding a `org.jboss.jbossfaces.JSF_CONFIG_NAME` context parameter to its `web.xml` file. For
example, to indicate that a Jakarta Server Faces app should use MyFaces 4.0.0 (assuming MyFaces 4.0.0 has been installed
on the server), the following context parameter would need to be added:

[source,xml,options="nowrap"]
----
<context-param>
  <param-name>org.jboss.jbossfaces.JSF_CONFIG_NAME</param-name>
  <param-value>myfaces-4.0.0</param-value>
</context-param>
----

If a Jakarta Server Faces app does not specify this context parameter, the default Jakarta Server Faces implementation
will be used for that app.

[[disallowing-doctype-declarations]]
== Disallowing DOCTYPE declarations

The following CLI commands can be used to disallow DOCTYPE declarations in Jakarta Server Faces deployments:

[source,options="nowrap"]
----
/subsystem=jsf:write-attribute(name=disallow-doctype-decl, value=true)
reload
----

This setting can be overridden for a particular Jakarta Server Faces deployment by adding the
`com.sun.faces.disallowDoctypeDecl` context parameter to the deployment's `web.xml` file:

[source,xml,options="nowrap"]
----
<context-param>
  <param-name>com.sun.faces.disallowDoctypeDecl</param-name>
  <param-value>false</param-value>
</context-param>
----
