[[JAXRS]]
= JAXRS subsystem configuration

The jaxrs subsystem presents RESTful facilities as defined by the Jakarta RESTful Web Services
project (https://projects.eclipse.org/projects/ee4j.jaxrs) and implemented
by the RESTEasy project (https://resteasy.github.io). 

jaxrs is a key facility and is implemented in the usual out of the box wildfly profiles, such as
standalone.xml, standalone-full.xml, etc.

*Required extension:*

[source,xml,options="nowrap"]
----
<extension module="org.jboss.as.jaxrs"/>
----

*Basic subsystem configuration example:*

jaxrs ships as an empty xml element:

[source,xml,options="nowrap"]
----
<subsystem xmlns="urn:jboss:domain:jaxrs:2.0"/>
----
but it can be expanded to configure parameters described in Section 3.4 "Configuration switches"
of the RESTEasy User Guide (https://resteasy.github.io/docs.html). For example:

[source,xml,options="nowrap"]

<subsystem xmlns="urn:jboss:domain:jaxrs:2.0">
    <resteasy-add-charset>true</resteasy-add-charset>
    <resteasy-gzip-max-input>17</resteasy-gzip-max-input>
    <resteasy-language-mapping>es : es,fr:fr,  en:en-US</resteasy-language-mapping>
    <resteasy-media-type-param-mapping>mt</resteasy-media-type-param-mapping>
    <resteasy-providers>com.bluemonkey.reader,com.bluemonkey.writer</resteasy-providers>
</subsystem>

*Note.* The use of hyphens in the parameter names is a Wildfly convention. The hyphens are translated into periods before
the parameters are passed into RESTEasy so that they conform to the RESTEasy parameter names.

For a discussion of the various parameters, see the RESTEasy User Guide.
The important thing to understand is that once a parameter is set, by way of the CLI interface, for example,
that parameter and its value will be passed to subsequent deployments as web.xml context parameters. Existing 
deployments are not affected.

A parameter value is of one of five types:

1. boolean
2. integer
3. string
4. list
5. map

The syntax of the first three is as usual. A list is comma separated, and
a map is a comma separated list of "key:value" elements. White space is ignored.

