[[Resource_adapters]]
= Resource adapters

Resource adapters are configured through the _resource-adapters_
subsystem. Declaring a new resource adapter consists of two separate
steps: You would need to deploy the .rar archive and define a resource
adapter entry in the subsystem.

[[resource-adapter-definitions]]
== Resource Adapter Definitions

The resource adapter itself is defined within the subsystem
_resource-adapters_:

[source, xml]
----
<subsystem xmlns="urn:jboss:domain:resource-adapters:1.0">
    <resource-adapters>
       <resource-adapter>
          <archive>eis.rar</archive>
          <!-- Resource adapter level config-property -->
          <config-property name="Server">localhost</config-property>
          <config-property name="Port">19000</config-property>
          <transaction-support>XATransaction</transaction-support>
          <connection-definitions>
             <connection-definition class-name="com.acme.eis.ra.EISManagedConnectionFactory"
                                    jndi-name="java:/eis/AcmeConnectionFactory"
                                    pool-name="AcmeConnectionFactory">
                <!-- Managed connection factory level config-property -->
                <config-property name="Name">Acme Inc</config-property>
                <pool>
                   <min-pool-size>10</min-pool-size>
                   <max-pool-size>100</max-pool-size>
                </pool>
                <security>
                   <application/>
                </security>
             </connection-definition>
         </connection-definitions>
         <admin-objects>
             <admin-object class-name="com.acme.eis.ra.EISAdminObjectImpl"
                           jndi-name="java:/eis/AcmeAdminObject">
                <config-property name="Threshold">10</config-property>
             </admin-object>
         </admin-objects>
       </resource-adapter>
    </resource-adapters>
</subsystem>
----

Note, that only JNDI bindings under java:/ or java:jboss/ are supported.

~(See~ `standalone/configuration/standalone.xml` ~)~

[[ra-using-security-domains]]
== Using security domains

Information about using security domains can be found at
https://community.jboss.org/wiki/JBossAS7SecurityDomainModel

[[automatic-activation-of-resource-adapter-archives]]
== Automatic activation of resource adapter archives

A resource adapter archive can be automatically activated with a
configuration by including an META-INF/ironjacamar.xml in the archive.

The schema can be found at
http://docs.jboss.org/ironjacamar/schema/ironjacamar_1_0.xsd

[[ra-component-reference]]
== Component Reference

The resource adapter subsystem is provided by the
http://www.jboss.org/ironjacamar[IronJacamar] project. For a detailed
description of the available configuration properties, please consult
the project documentation.

* IronJacamar homepage: http://www.jboss.org/ironjacamar
* Project Documentation: http://www.jboss.org/ironjacamar/docs
* Schema description:
http://docs.jboss.org/ironjacamar/userguide/1.0/en-US/html/deployment.html#deployingra_descriptor
