[[Simple_configuration_subsystems]]
= Simple configuration subsystems

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

The following subsystems currently have no configuration beyond their root
element in the configuration

[source,xml,options="nowrap"]
----
<subsystem xmlns="urn:wildfly:jakarta-data:preview:1.0"/>
<subsystem xmlns="urn:jboss:domain:jdr:1.0"/>
<subsystem xmlns="urn:jboss:domain:mvc-krazo:1.0"/>
<subsystem xmlns="urn:jboss:domain:pojo:1.0"/>
<subsystem xmlns="urn:jboss:domain:sar:1.0"/>
----

The presence of each of these turns on a piece of functionality:

[cols=",",options="header"]
|=======================================================================
|Name |Description


|jakarta-data| Provides support for use of Jakarta Data in deployments. Currently provided at xref:Admin_Guide.adoc#Feature_stability_levels[`preview` stability].

|jdr |Enables the gathering of diagnostic data for use in remote
analysis of error conditions. Although the data is in a simple format
and could be useful to anyone, it is primarily useful for JBoss EAP
subscribers who would provide the data to Red Hat when requesting
support.

|mvc-krazo| Provides support for use of Jakarta MVC in deployments. Currently provided at xref:Admin_Guide.adoc#Feature_stability_levels[`preview` stability].

|pojo |Enables the deployment of applications containing JBoss
Microcontainer services, as supported by previous versions of JBoss
Application Server.

|sar |Enables the deployment of .SAR archives containing MBean services,
as supported by previous versions of JBoss Application Server.
|=======================================================================
