/*
 * Generated by XDoclet - Do not edit!
 */
package org.jboss.as.test.integration.ejb.entity.cmp.optimisticlock.interfaces;

/**
 * Local interface for CmpEntity.
 */
public interface CmpEntityLocal
        extends javax.ejb.EJBLocalObject {

    java.lang.Integer getId();

    java.lang.String getStringGroup1();

    void setStringGroup1(java.lang.String stringField);

    java.lang.Integer getIntegerGroup1();

    void setIntegerGroup1(java.lang.Integer value);

    java.lang.Double getDoubleGroup1();

    void setDoubleGroup1(java.lang.Double value);

    java.lang.String getStringGroup2();

    void setStringGroup2(java.lang.String stringField);

    java.lang.Integer getIntegerGroup2();

    void setIntegerGroup2(java.lang.Integer value);

    java.lang.Double getDoubleGroup2();

    void setDoubleGroup2(java.lang.Double value);

    java.lang.Long getVersionField();

    void setVersionField(java.lang.Long value);

}
