[[jboss-ejb-client]]
= jboss-ejb-client
<jboss-ejb-client /> - EJB Client

The _<jboss-ejb-client />_ element in a wildfly-config.xml file can be used to specify EJB Client configuration. This element is from the “urn:jboss:wildfly-client-ejb:3.0” namespace, e.g.

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<configuration>
...
    <jboss-ejb-client xmlns="urn:jboss:wildfly-client-ejb:3.0">
       ...
    </jboss-ejb-client>
...
</configuration>
----

This section describes the child elements and attributes that can be configured within this element.

The _<jboss-ejb-client /> element can optionally contain the following three child elements, as described in the next sections:

* *<invocation-timeout />*
* *<global-interceptors />*
* *<connections />*


== <invocation-timeout />

This element is used to specify an EJB invocation timeout. It has one attribute which is required:

[cols=",",options="header"]
|====
| Attribute | Description
| seconds | The timeout, in seconds, for the EJB handshake or method invocation request/response cycle. The invocation of any method throws a {{java.util.concurrent.TimeoutException}} if the execution takes longer than the timeout period. The server side will not be interrupted. \\ |
|====

== <global-interceptors />

This element is used to specify global EJB client interceptors. It can contain any number of _<interceptor />_ elements.

== <interceptor />

This element is used to specify an EJB client interceptor. It has two attributes:

[cols=",",options="header"]
|====
| Attribute | Description
| class | The name of a class that implements the {{org.jboss.ejb.client.EJBClientInterceptor}} interface.
| module | The optional name of the module that should be used to load the interceptor class.
|====

== <connections />

This element is used to specify EJB client connections. It can contain any number of _<connection />_ elements.

== <connection />

This element is used to specify an EJB client connection. It has one required attribute. It can also optionally contain an _<interceptors />_ element.

[cols=",",options="header"]
|====
| Attribute | Description
| uri | The connection destination URI.
|====

== <interceptors />

This element is used to specify EJB client interceptors and can contain any number of _<interceptor />_ elements.