<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="AnotherService" targetNamespace="http://jbossws.org/SchemaLocationsRewrite/anotherservice"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://jbossws.org/SchemaLocationsRewrite/anotherservice"
                  xmlns:schema="http://jbossws.org/SchemaLocationsRewrite"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xs:schema elementFormDefault="unqualified" targetNamespace="http://jbossws.org/SchemaLocationsRewrite"
                   version="1.0">
            <xs:import namespace="http://jbossws.org/SchemaLocationsRewrite" schemaLocation="SimpleService.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="sayHelloResponse">
        <wsdl:part element="schema:sayHelloResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="sayHello">
        <wsdl:part element="schema:sayHello" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="AnotherService">
        <wsdl:operation name="sayHello">
            <wsdl:input message="tns:sayHello" name="sayHello">
            </wsdl:input>
            <wsdl:output message="tns:sayHelloResponse" name="sayHelloResponse">
            </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="AnotherServiceSoapBinding" type="tns:AnotherService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="sayHello">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="sayHello">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="sayHelloResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="AnotherService">
        <wsdl:port binding="tns:AnotherServiceSoapBinding" name="AnotherServicePort">
            <soap:address location="http://server.domain:8080/schema-location-rewrite/AnotherService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>