//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.07.21 at 10:48:55 AM CEST
//

package org.jboss.as.test.integration.osgi.jaxb.bundle;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for courseBooking complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="courseBooking">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}company"/>
 *         &lt;element ref="{}student" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="courseReference" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="courseDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="invoiceReference" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="totalPrice" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "courseBooking", propOrder = { "company", "student" })
public class CourseBooking {

    @XmlElement(required = true)
    protected CompanyType company;
    @XmlElement(required = true)
    protected List<StudentType> student;
    @XmlAttribute(required = true)
    protected String courseReference;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar courseDate;
    @XmlAttribute(required = true)
    protected String invoiceReference;
    @XmlAttribute(required = true)
    protected BigDecimal totalPrice;

    /**
     * Gets the value of the company property.
     *
     * @return possible object is {@link CompanyType }
     *
     */
    public CompanyType getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     *
     * @param value allowed object is {@link CompanyType }
     *
     */
    public void setCompany(CompanyType value) {
        this.company = value;
    }

    /**
     * Gets the value of the student property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the student
     * property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getStudent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link StudentType }
     *
     *
     */
    public List<StudentType> getStudent() {
        if (student == null) {
            student = new ArrayList<StudentType>();
        }
        return this.student;
    }

    /**
     * Gets the value of the courseReference property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCourseReference() {
        return courseReference;
    }

    /**
     * Sets the value of the courseReference property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCourseReference(String value) {
        this.courseReference = value;
    }

    /**
     * Gets the value of the courseDate property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getCourseDate() {
        return courseDate;
    }

    /**
     * Sets the value of the courseDate property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setCourseDate(XMLGregorianCalendar value) {
        this.courseDate = value;
    }

    /**
     * Gets the value of the invoiceReference property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getInvoiceReference() {
        return invoiceReference;
    }

    /**
     * Sets the value of the invoiceReference property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setInvoiceReference(String value) {
        this.invoiceReference = value;
    }

    /**
     * Gets the value of the totalPrice property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the value of the totalPrice property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setTotalPrice(BigDecimal value) {
        this.totalPrice = value;
    }

}
